package com.project.servicecode.service.DataBase.USER_LIST;

import com.project.servicecode.service.DataBase.USER_LIST.model.UserList;
import com.project.servicecode.service.DataBase.USER_LIST.model.UserListExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    long countByExample(UserListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int deleteByExample(UserListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int insert(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int insertSelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    List<UserList> selectByExample(UserListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    UserList selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserList record, @Param("example") UserListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int updateByExample(@Param("record") UserList record, @Param("example") UserListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int updateByPrimaryKeySelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_LIST
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    int updateByPrimaryKey(UserList record);
}