package com.project.servicecode.service.DataBase.USER_LIST.model;

import java.util.Date;

public class UserList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.USER_ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.USER_NAME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.PASSWORD
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.USER_TYPE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.ENABLE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.REFERRER
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private String referrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.CREATED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private Date lastModifiedDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_LIST.LAST_LOGIN_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    private Date lastLoginDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.USER_ID
     *
     * @return the value of USER_LIST.USER_ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.USER_ID
     *
     * @param userId the value for USER_LIST.USER_ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.ID
     *
     * @return the value of USER_LIST.ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.ID
     *
     * @param id the value for USER_LIST.ID
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.USER_NAME
     *
     * @return the value of USER_LIST.USER_NAME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.USER_NAME
     *
     * @param userName the value for USER_LIST.USER_NAME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.PASSWORD
     *
     * @return the value of USER_LIST.PASSWORD
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.PASSWORD
     *
     * @param password the value for USER_LIST.PASSWORD
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.USER_TYPE
     *
     * @return the value of USER_LIST.USER_TYPE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.USER_TYPE
     *
     * @param userType the value for USER_LIST.USER_TYPE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.ENABLE
     *
     * @return the value of USER_LIST.ENABLE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.ENABLE
     *
     * @param enable the value for USER_LIST.ENABLE
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setEnable(String enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.REFERRER
     *
     * @return the value of USER_LIST.REFERRER
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public String getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.REFERRER
     *
     * @param referrer the value for USER_LIST.REFERRER
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setReferrer(String referrer) {
        this.referrer = referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.CREATED_DATETIME
     *
     * @return the value of USER_LIST.CREATED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.CREATED_DATETIME
     *
     * @param createdDatetime the value for USER_LIST.CREATED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.LAST_MODIFIED_DATETIME
     *
     * @return the value of USER_LIST.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public Date getLastModifiedDatetime() {
        return lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.LAST_MODIFIED_DATETIME
     *
     * @param lastModifiedDatetime the value for USER_LIST.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setLastModifiedDatetime(Date lastModifiedDatetime) {
        this.lastModifiedDatetime = lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_LIST.LAST_LOGIN_DATETIME
     *
     * @return the value of USER_LIST.LAST_LOGIN_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public Date getLastLoginDatetime() {
        return lastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_LIST.LAST_LOGIN_DATETIME
     *
     * @param lastLoginDatetime the value for USER_LIST.LAST_LOGIN_DATETIME
     *
     * @mbg.generated Sun Aug 29 17:58:56 CST 2021
     */
    public void setLastLoginDatetime(Date lastLoginDatetime) {
        this.lastLoginDatetime = lastLoginDatetime;
    }
}